name: discharge
version: 0.02.1
author: Dušan Kasan <dusan@kasan.sk>
description: Dependency injection and service container
homepage: https://github.com/DusanKasan/Discharge
documentation: https://github.com/DusanKasan/Discharge
dependencies:
  mock: '>=0.11.0+1 <0.12.0'
  unittest: '>=0.11.0+1 <0.12.0'
  xml: '>=2.1.1 <3.0.0'
